version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    stdin_open: true
    volumes:
      - ./frontend/src:/usr/src/app/src
      - type: bind
        source: ./frontend/package.json
        target: /usr/src/app/package.json
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - type: bind
        source: ./backend/package.json
        target: /usr/src/app/package.json
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: sector_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=sector
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
